---
- hosts: all
  tasks: 

          - name: install ftp package
            yum:  name=vsftpd  state=latest 


          - name: start the ftp srervice
            service: name=vsftpd  state=started

          - name: enable the ftp  srervice
            service: name=vsftpd  enabled=yes

          - name: copy the index.html file on the ftp servers
            copy: src=/root/index.html   dest=/var/ftp/pub 

          - name: grant the full permissions on the  index.html file in  the ftp  servers
            file:  dest=/var/ftp/pub/index.html    mode=777
