---
- hosts: all
  tasks: 
          - name: create a multi users with loop method 
            user:
                   name: "{{ item }}"
                   state: present
            loop:
                 - user1
                 - user2
                 - user3
                 - user4
                 - user5
                 - user6
                 - user7
                 - user8
                 - user9
