---
- hosts: all
  tasks:

          - name: install http package
            yum:  name=httpd  state=latest


          - name: start the http srervice
            service: name=httpd  state=started

          - name: enable the http srervice
            service: name=httpd  enabled=yes

          - name: copy the index.html file on the web servers
            copy: src=/root/index.html   dest=/var/www/html

          - name: grant the full permissions on the  index.html file in  the web servers
            file:  dest=/var/www/html/index.html    mode=777
